# Generated by Django 5.2.17 on 2026-10-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WipGenerationMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_generated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WipUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('gaines', 'gaines'), ('earlgray', 'earlgray')], max_length=20)),
                ('usn', models.CharField(max_length=40)),
                ('model_name', models.CharField(max_length=60)),
                ('sku_model', models.CharField(max_length=80)),
                ('mo', models.CharField(max_length=40)),
                ('upn', models.CharField(max_length=40)),
                ('stage', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Testing', 'Testing'), ('Failed', 'Failed'), ('Offline', 'Offline')], max_length=20)),
                ('pod', models.CharField(blank=True, default='', max_length=40)),
                ('error_code', models.CharField(blank=True, default='', max_length=20)),
                ('error_description', models.CharField(blank=True, default='', max_length=120)),
                ('stay_time_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['family', 'stage'], name='miapi_wipun_family_4dd219_idx'), models.Index(fields=['family', 'status'], name='miapi_wipun_family_7df74a_idx')],
            },
        ),
    ]
