# Generated by Django 5.2.17 on 2026-10-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wipunit',
            new_name='wip_units_family_310f1f_idx',
            old_name='miapi_wipun_family_4dd219_idx',
        ),
        migrations.RenameIndex(
            model_name='wipunit',
            new_name='wip_units_family_e4334b_idx',
            old_name='miapi_wipun_family_7df74a_idx',
        ),
        migrations.AlterField(
            model_name='wipunit',
            name='family',
            field=models.CharField(choices=[('proyecto_a', 'proyecto_a'), ('proyecto_b', 'proyecto_b')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='wipgenerationmeta',
            table='wip_simulation_state',
        ),
        migrations.AlterModelTable(
            name='wipunit',
            table='wip_units',
        ),
    ]
